version: "3.8"
services:
  web:
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app
    # restart: always

  nginx:
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.certificates/nginx:/etc/letsencrypt/live:rw
      # - ./.certificates/certbot/www/:/var/www/certbot/:ro
      # - ./.certificates/certbot/conf/:/etc/letsencrypt/:rw
    # restart: always
    # command: ["tail", "-f", "/dev/null"]

  # certbot:
  #   container_name: certbot-server
  #   image: certbot/certbot:latest
  #   volumes: 
  #     - ./.log/certbot/www/:/var/www/certbot/:rw
  #     - ./.log/certbot/conf/:/etc/letsencrypt/:rw
  #   restart: always
